//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class PowerUpController : MonoBehaviour
{
	private List<string> powerUps = new List<string> ();
	private float respawnTimer = 0;
	[SerializeField] private float timeToRespawn = 5;
	private bool isTrigger = true;

	public PowerUpController ()
	{
		powerUps.Add ("reparation");
		powerUps.Add ("projRouge");
		powerUps.Add ("projVert");
		powerUps.Add ("projBleu");
	}

	void OnTriggerEnter(Collider other)
	{
		if (isTrigger) {
			if (other.gameObject.CompareTag ("Car_Collider")) {
				CarController car = other.GetComponentInParent<CarController> ();

				//int n = Random.Range (0, powerUps.Count);
				int n = 0;
				switch (powerUps [n]) {
				case "reparation":
					car.Repair (1f);
					break;
				case "projRouge":
					//car.projectilePrefab.projectileType = Projectile.ProjType.Red;
					break;
				case "projVert":
					//car.projectilePrefab.projectileType = Projectile.ProjType.Green;
					break;
				case "projBleu":
					//car.projectilePrefab.projectileType = Projectile.ProjType.Blue;
					break;
				default:
					break;
				}

				isTrigger = false;
				gameObject.GetComponent<Renderer> ().material.color = Color.red;
			}
		}
	}

	void Update()
	{
		if (!isTrigger) {
			respawnTimer += Time.deltaTime;
			if (respawnTimer >= timeToRespawn) {
				isTrigger = true;
				gameObject.GetComponent<Renderer> ().material.color = Color.green;
				respawnTimer = 0;
			}
		} else if (gameObject.GetComponent<Renderer> ().material.color != Color.green) {
			gameObject.GetComponent<Renderer> ().material.color = Color.green;
		}
	}
}

