//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class ObstacleController : MonoBehaviour
{
	[SerializeField] [Range(0f, 1f)] float _health =  1f;
    public GameObject deathFX;

	public float health
	{
		get
		{
			return _health;
		}
	}

	public void Damage(float dmg)
	{
		_health = Mathf.Clamp(health - dmg, 0f, 1f);
	}

	void Update()
	{
		if (health <= 0f) {
            var fx = Instantiate(deathFX, transform.position, transform.rotation) as GameObject;
            Destroy(fx.gameObject, 20.0f);
			Destroy(gameObject);
		}
	}
}

